name: Rancher Reaper
description: |
  Automatically delete hosts from Rancher if they have been terminated in AWS.
version: 0.5.0
category: Automation
maintainer: Oguz Kilcan <oguz.kilcan@gmail.com>
license: MIT
projectURL: https://github.com/ouzklcn/rancher-reaper