version: '2'
services:
  rancher-reaper:
    image: ouzklcn/rancher-reaper:v0.5.0
    tty: true
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment